export const config = {
  port: process.env.PORT,
  DB_URL: process.env.DB_URL,
  accessKey: process.env.ACCESSTOKEN_SECRATE,
  refereshKey: process.env.REFERESHTOKEN_SECRATE,
  accessExpiry: process.env.ACCESSTOKEN_EXPIRY,
  SUCCESS: 200,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_VERIFIED: 410,
  INTERNAL_SERVER_ERROR: 500,
  NOT_ALLOWED: 405,
  NO_CONTENT: 204,
};
